# config/secrets.yml
development:
  secret_key_base: <%= ENV["development_secret_key_base"] %>

test:
  secret_key_base: <%= ENV["test_secret_key_base"] %>

production:
  secret_key_base: <%= ENV["production_secret_key_base"] %>
